import enum
import uuid
from datetime import datetime
from decimal import Decimal

from sqlalchemy import Boolean, DateTime, Enum, ForeignKey, Numeric, String, Text, UniqueConstraint
from sqlalchemy.orm import Mapped, mapped_column

from app.database import Base
from app.domain.business_time import business_now_naive

AMOUNT_PRECISION = 12
AMOUNT_SCALE = 2


class SaleSource(str, enum.Enum):
    MANUAL = "manual"
    CSV = "csv"
    WEBHOOK = "webhook"
    # A sale generated by the in-product local demo simulator (see
    # app/services/demo_simulator.py) — never a real payment. Kept distinct
    # from WEBHOOK so demo data can always be identified and safely reset
    # without touching a real webhook-ingested sale.
    DEMO = "demo"


class SaleStatus(str, enum.Enum):
    SUCCEEDED = "succeeded"
    PENDING = "pending"
    FAILED = "failed"
    REFUNDED = "refunded"
    PARTIALLY_REFUNDED = "partially_refunded"


class PaymentMethod(str, enum.Enum):
    """The closed set of payment methods selectable through the sale
    create/update API. `Sale.payment_method` itself stays a plain string
    column, not an enum, because webhook-ingested sales may legitimately
    carry a payment-provider-specific value outside this set — validation
    against this enum applies only at the API boundary a human fills in."""

    CARD = "card"
    CASH = "cash"
    OTHER = "other"


class SaleCurrency(str, enum.Enum):
    """The closed set of transaction currencies selectable through the sale
    create/update API — see app.domain.demo_business for why this is
    separate from tax jurisdiction. `Sale.currency` itself stays a plain
    3-letter string column, not an enum, because webhook and CSV ingestion
    may legitimately carry a currency this demo's manual-entry UI doesn't
    offer yet (same reasoning as `PaymentMethod` above)."""

    ILS = "ILS"
    USD = "USD"
    EUR = "EUR"


class TaxTreatment(str, enum.Enum):
    """How Israeli VAT applies to a sale — independent of `currency` (see
    app.domain.demo_business: an Israeli business charging in USD is still
    taxed under Israeli VAT rules). `standard` is ordinary 18% VAT-inclusive
    pricing; `zero_rate` is a sale VAT applies to at a 0% rate (e.g. certain
    exports); `exempt` is a sale VAT law doesn't apply to at all. zero_rate
    and exempt both produce a VAT amount of 0 — the field exists so the
    *reason* stays on the record, not just the number."""

    STANDARD = "standard"
    ZERO_RATE = "zero_rate"
    EXEMPT = "exempt"


class DocumentStatus(str, enum.Enum):
    """Tracks the receipt/tax document issued *to the customer* for this
    sale — an outgoing document, never one received from a supplier."""

    PENDING = "pending"
    ISSUED = "issued"
    FAILED = "failed"
    NOT_REQUIRED = "not_required"


class Sale(Base):
    """A single customer sale/revenue transaction — the central domain
    record of the app. Money fields: `gross_amount` is what the customer
    paid, `vat_amount` is the portion of that collected on behalf of the
    tax authority (not real business revenue), `processing_fee` is what the
    payment provider kept, and `net_amount` = gross - vat - fee is the
    actual revenue the business nets from the sale."""

    __tablename__ = "sales"
    __table_args__ = (UniqueConstraint("source_provider", "external_id", name="uq_sales_source_provider_external_id"),)

    id: Mapped[str] = mapped_column(String(36), primary_key=True, default=lambda: str(uuid.uuid4()))

    external_id: Mapped[str | None] = mapped_column(String(255), nullable=True)
    source_provider: Mapped[str | None] = mapped_column(String(64), nullable=True)
    source: Mapped[SaleSource] = mapped_column(Enum(SaleSource, native_enum=False), nullable=False, default=SaleSource.MANUAL)
    status: Mapped[SaleStatus] = mapped_column(
        Enum(SaleStatus, native_enum=False), nullable=False, default=SaleStatus.SUCCEEDED
    )
    # Naive business-local (Asia/Jerusalem) wall-clock time — every creation
    # path sets this explicitly, so `default=` is only a schema-level
    # fallback; see app.domain.business_time for the naive-timestamp
    # convention this follows.
    occurred_at: Mapped[datetime] = mapped_column(DateTime, nullable=False, default=business_now_naive)

    customer_name: Mapped[str] = mapped_column(String(255), nullable=False)
    customer_contact: Mapped[str | None] = mapped_column(String(255), nullable=True)
    service_name: Mapped[str] = mapped_column(String(255), nullable=False)
    description: Mapped[str | None] = mapped_column(Text, nullable=True)

    gross_amount: Mapped[Decimal] = mapped_column(Numeric(AMOUNT_PRECISION, AMOUNT_SCALE), nullable=False)
    vat_amount: Mapped[Decimal | None] = mapped_column(Numeric(AMOUNT_PRECISION, AMOUNT_SCALE), nullable=True)
    processing_fee: Mapped[Decimal | None] = mapped_column(Numeric(AMOUNT_PRECISION, AMOUNT_SCALE), nullable=True)
    net_amount: Mapped[Decimal] = mapped_column(Numeric(AMOUNT_PRECISION, AMOUNT_SCALE), nullable=False)
    refunded_amount: Mapped[Decimal | None] = mapped_column(Numeric(AMOUNT_PRECISION, AMOUNT_SCALE), nullable=True)
    currency: Mapped[str] = mapped_column(String(3), nullable=False, default="ILS")
    payment_method: Mapped[str | None] = mapped_column(String(50), nullable=True)

    # `tax_treatment` is nullable for one reason only: a legacy sale migrated
    # from before this field existed whose old vat_amount is ambiguous (see
    # the migration) is left NULL with `tax_treatment_needs_review=True`,
    # rather than the migration inventing a value it can't actually know.
    # Every sale created after this field's introduction always gets a
    # concrete value — enforced at the API boundary (see app/schemas/sale.py),
    # never left NULL by choice.
    tax_treatment: Mapped[str | None] = mapped_column(
        Enum(TaxTreatment, native_enum=False), nullable=True
    )
    tax_treatment_needs_review: Mapped[bool] = mapped_column(Boolean, nullable=False, default=False)
    # A snapshot of the VAT rate actually used to compute this sale's
    # vat_amount at the time it was calculated — see
    # app/services/tax/vat.py:vat_rate_snapshot. A future change to the
    # business's configured standard rate must never change what a past sale
    # is understood to have charged.
    vat_rate: Mapped[Decimal | None] = mapped_column(Numeric(6, 4), nullable=True)

    document_status: Mapped[DocumentStatus] = mapped_column(
        Enum(DocumentStatus, native_enum=False), nullable=False, default=DocumentStatus.PENDING
    )
    document_number: Mapped[str | None] = mapped_column(String(100), nullable=True)
    document_url: Mapped[str | None] = mapped_column(String(500), nullable=True)

    raw_description: Mapped[str | None] = mapped_column(Text, nullable=True)
    import_batch_id: Mapped[str | None] = mapped_column(
        String(36), ForeignKey("import_batches.id", ondelete="SET NULL"), nullable=True
    )

    created_at: Mapped[datetime] = mapped_column(DateTime, default=datetime.utcnow, nullable=False)
    updated_at: Mapped[datetime] = mapped_column(
        DateTime, default=datetime.utcnow, onupdate=datetime.utcnow, nullable=False
    )

    def revenue_contribution(self) -> Decimal:
        """The amount of `net_amount` that actually counts toward revenue
        totals: zero for a pending/failed sale, the full net amount for a
        succeeded one, and net minus whatever was refunded otherwise."""
        if self.status in (SaleStatus.PENDING, SaleStatus.FAILED):
            return Decimal("0")
        if self.status == SaleStatus.REFUNDED:
            return Decimal("0")
        refunded = self.refunded_amount or Decimal("0")
        return max(self.net_amount - refunded, Decimal("0"))
