"""create expenses table

Revision ID: 6a7684b67742
Revises: 
Create Date: 2026-08-30 01:03:14.927851

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '6a7684b67742'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('expenses',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('business_name', sa.String(length=255), nullable=False),
    sa.Column('receipt_number', sa.String(length=100), nullable=True),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('vat_amount', sa.Float(), nullable=True),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('category', sa.Enum('GROCERIES', 'DINING', 'TRANSPORT', 'UTILITIES', 'HEALTH', 'SHOPPING', 'ENTERTAINMENT', 'TRAVEL', 'HOUSING', 'OTHER', name='expensecategory', native_enum=False), nullable=False),
    sa.Column('expense_date', sa.Date(), nullable=False),
    sa.Column('payment_method', sa.String(length=50), nullable=True),
    sa.Column('receipt_image_path', sa.String(length=255), nullable=True),
    sa.Column('extraction_confidence', sa.Float(), nullable=True),
    sa.Column('extraction_status', sa.Enum('MANUAL', 'PENDING', 'EXTRACTED', 'CONFIRMED', 'FAILED', name='extractionstatus', native_enum=False), nullable=False),
    sa.Column('notes', sa.String(length=1000), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('expenses')
    # ### end Alembic commands ###
