import { Link } from 'react-router-dom'
import { ArrowLeft, Check, ChartNoAxesCombined, Zap, ShieldCheck, MessageSquare, PlugZap, ChevronDown } from 'lucide-react'
import logo from '../assets/investment-logo.svg'
import './PublicPages.css'
import { useLandingMotion } from '../hooks/useLandingMotion'

export function PublicBrand() { return <Link to="/" className="public-brand"><img src={logo} alt=""/><span>מנהל הכנסות<small>מבית SYDNEY</small></span></Link> }
export function ProductPreview() { return <div className="product-preview" aria-label="תצוגה להמחשה של לוח ההכנסות"><div className="preview-top"><span>סקירת העסק</span><span className="preview-pill">נתונים להמחשה · ספטמבר</span></div><div className="preview-numbers"><div><small>תקבולים נטו לאחר ניכויים</small><strong>₪24,850<span>.00</span></strong><em>↗ 12.4% לעומת החודש הקודם</em></div><div className="preview-count"><small>מכירות מוצלחות</small><b>128</b></div></div><div className="preview-chart"><div className="chart-grid"/><svg viewBox="0 0 600 160" preserveAspectRatio="none" aria-hidden="true"><defs><linearGradient id="fill" x1="0" x2="0" y1="0" y2="1"><stop stopColor="#2bd5b4" stopOpacity=".3"/><stop offset="1" stopColor="#2bd5b4" stopOpacity="0"/></linearGradient></defs><path d="M0 130 C30 125 40 90 70 103 S120 135 150 89 S190 110 230 65 S280 90 320 45 S355 70 400 37 S435 55 480 20 S550 40 600 8 L600 160 L0 160Z" fill="url(#fill)"/><path d="M0 130 C30 125 40 90 70 103 S120 135 150 89 S190 110 230 65 S280 90 320 45 S355 70 400 37 S435 55 480 20 S550 40 600 8" stroke="#39dab6" strokeWidth="3" fill="none"/></svg></div><div className="preview-bottom"><span><Check size={15}/> העסקה התקבלה</span><span>ייעוץ עסקי</span><b>₪850.00</b></div></div> }
const features = [
 {icon:ChartNoAxesCombined,title:'התמונה המלאה, במבט אחד',text:'מכירות, מע״מ, עמלות וזיכויים — עם פירוט שמבהיר איך מתקבל כל סכום.'},
 {icon:Zap,title:'מכירה חדשה. עדכון אוטומטי.',text:'חיבור למערכת התשלומים מאפשר לקלוט עסקאות בלי להזין כל מכירה מחדש.'},
 {icon:ShieldCheck,title:'יודעים מה דורש טיפול',text:'תשלומים שנכשלו ומסמכים חסרים מקבלים מקום ברור במרכז החריגים.'},
 {icon:MessageSquare,title:'שואלים את הנתונים שלכם',text:'איזה שירות מכר הכי הרבה? כמה נכנס החודש? העוזר עוזר למצוא תשובות.'},
]
export function HomePage() {
 const motionRef = useLandingMotion()
 return <div ref={motionRef} className="public-site" dir="rtl">
<header className="public-header"><PublicBrand/><nav aria-label="ניווט באתר"><a href="#features">יכולות</a><a href="#how">איך זה עובד</a><a href="#connections">חיבורים</a><a href="#faq">שאלות נפוצות</a></nav><div className="header-actions"><Link to="/login">התחברות</Link><Link className="public-button small" to="/signup">פתיחת חשבון <ArrowLeft size={16}/></Link></div></header>
<main><section className="public-hero"><div className="hero-image"/><div className="hero-inner"><div className="hero-copy"><span className="eyebrow">פחות התעסקות. יותר בהירות.</span><h1>העסק מכר.<br/>אתם כבר<br/><span>בתמונה.</span></h1><p>כל המכירות, התקבולים והחריגים של העסק במקום אחד. כדי שתדעו מה נכנס, מה השתנה ומה הצעד הבא.</p><div className="hero-actions"><Link to="/signup" className="public-button">מתחילים לנהל הכנסות <ArrowLeft size={18}/></Link><a className="public-button ghost" href="#preview">לראות איך זה עובד</a></div><div className="hero-notes"><span><Check size={15}/> מותאם לעברית</span><span><Check size={15}/> תמונה כספית ברורה</span><span><Check size={15}/> פחות עבודה ידנית</span></div></div><div className="hero-product" id="preview"><div className="floating-label"><Zap size={16}/> מהתשלום לתמונה המלאה</div><ProductPreview/><p className="preview-caption">המחשת המוצר · הנתונים אינם נתוני עסק אמיתי</p></div></div><div className="hero-bottom"><span>נבנה לעסקים קטנים. חושב על הפרטים הגדולים.</span><a href="#features" aria-label="לגלות את היכולות"><ChevronDown size={20}/></a></div></section>
<section className="public-section features" id="features"><div className="section-heading"><span className="eyebrow">כל העסק, בפרספקטיבה</span><h2>המספרים במקום אחד.<br/>הראש פנוי לעסק.</h2><p>פחות מעבר בין דוחות ומערכות. יותר זמן להבין מה עובד ולפעול בהתאם.</p></div><div className="feature-grid">{features.map(f=><article key={f.title}><f.icon size={25}/><h3>{f.title}</h3><p>{f.text}</p></article>)}</div></section>
<section className="public-section how-section" id="how"><div className="section-heading"><span className="eyebrow">מתחברים. מוכרים. רואים.</span><h2>מהעסקה הראשונה,<br/>הכול מתחבר.</h2></div><div className="steps">{[['01','מחברים את מקור המכירות','מגדירים חיבור למערכת התשלומים בעזרת ממשק החיבורים.'],['02','העסקאות נקלטות','פרטי הלקוח, השירות והתשלום מתרכזים ברשימת המכירות.'],['03','רואים את מצב העסק','עוקבים אחרי הכנסות ומגמות ומטפלים בחריגים בזמן.']].map(([n,t,d])=><article key={n}><span>{n}</span><h3>{t}</h3><p>{d}</p></article>)}</div></section>
<section className="public-section connection-section" id="connections"><div className="connection-art" aria-hidden="true"><div><PlugZap size={38}/></div><i/><div><img src={logo} alt=""/></div><i/><div><ChartNoAxesCombined size={38}/></div></div><div><span className="eyebrow">המערכות שלכם, יחד</span><h2>המידע מגיע.<br/>אתם ממשיכים לעבוד.</h2><p>המוצר מרכז מכירות ממקורות שונים ומכין את הנתונים לניתוח במקום אחד. חיבורים ישירים לספקי תשלומים וקופות יתווספו בהדרגה.</p><Link to="/signup" className="text-link">פותחים חשבון ומתחילים <ArrowLeft size={18}/></Link></div></section>
<section className="public-section faq-section" id="faq"><div><span className="eyebrow">לפני שמתחילים</span><h2>שאלות טובות.<br/>תשובות פשוטות.</h2></div><div className="faq-list">{[['צריך להעלות כל קבלה ידנית?','לאחר הגדרת חיבור מתאים, פרטי העסקאות יכולים להיקלט אוטומטית. אפשר גם להזין מכירה ידנית במערכת.'],['האם המערכת מחליפה רואה חשבון?','המערכת מרכזת את נתוני המכירות והתקבולים. היא אינה מחליפה רואה חשבון או שירות הנהלת חשבונות.'],['מה ההבדל בין תקבולים נטו לרווח?','התקבולים מוצגים לאחר הניכויים המפורטים במערכת. הם אינם רווח נקי, כי הוצאות העסק אינן נכללות בחישוב.'],['מה קורה אחרי ההרשמה?','מאמתים את כתובת האימייל ומתחברים. המוצר נמצא בשלב ההרצה; הגישה לסביבת העסק נפתחת לאחר שיוך החשבון לעסק.']].map(([q,a])=><details key={q}><summary>{q}<ChevronDown size={18}/></summary><p>{a}</p></details>)}</div></section>
<section className="public-cta"><span className="eyebrow">פחות סימני שאלה</span><h2>הצעד הבא של העסק<br/>מתחיל בתמונה ברורה.</h2><Link to="/signup" className="public-button">פתיחת חשבון <ArrowLeft size={18}/></Link></section></main><footer className="public-footer"><PublicBrand/><span>© {new Date().getFullYear()} Sydney · מנהל הכנסות</span><Link to="/login">כבר יש חשבון? מתחברים</Link></footer></div> }
