import userEvent from '@testing-library/user-event'
import { delay, http, HttpResponse } from 'msw'
import { describe, expect, it } from 'vitest'

import i18n from '../../i18n'
import { UploadReceiptPage } from '../UploadReceiptPage'
import { server } from '../../test/msw/server'
import { renderWithProviders, screen, waitFor, waitForElementToBeRemoved } from '../../test/test-utils'

const UPLOAD_URL = 'http://localhost:8000/api/receipts/upload'
const CONFIRM_URL = 'http://localhost:8000/api/receipts/confirm'
const CAPABILITIES_URL = 'http://localhost:8000/api/system/capabilities'

function fakeReceiptFile() {
  return new File(['fake-image-bytes'], 'receipt.png', { type: 'image/png' })
}

async function selectFile(user: ReturnType<typeof userEvent.setup>) {
  const fileInput = screen.getByLabelText('בחירת תמונה', { selector: 'input' })
  await user.upload(fileInput, fakeReceiptFile())
}

const successfulExtraction = {
  upload_id: 'upload-1',
  receipt_image_url: '/uploads/upload-1.png',
  extraction_succeeded: true,
  extracted_data: {
    business_name: 'Paz Gas Station',
    receipt_number: '80513',
    date: '2026-08-22',
    total: '60.13',
    vat: '8.74',
    currency: 'ILS',
    category: 'transport',
    confidence: 0.82,
    warnings: [],
  },
  error_message: null,
}

describe('UploadReceiptPage', () => {
  it('shows a loading state while analyzing, then the confirmation form', async () => {
    const user = userEvent.setup()
    server.use(
      http.post(UPLOAD_URL, async () => {
        await delay(30)
        return HttpResponse.json(successfulExtraction)
      }),
    )

    renderWithProviders(<UploadReceiptPage />)
    await selectFile(user)

    expect(await screen.findByText('מנתח את הקבלה...')).toBeInTheDocument()
    await waitForElementToBeRemoved(() => screen.queryByText('מנתח את הקבלה...'))

    expect(screen.getByText('סקירה ואישור')).toBeInTheDocument()
    expect(screen.getByDisplayValue('Paz Gas Station')).toBeInTheDocument()
  })

  it('shows a clear error state when the upload fails', async () => {
    const user = userEvent.setup()
    server.use(
      http.post(UPLOAD_URL, () =>
        HttpResponse.json({ detail: 'Unsupported file type' }, { status: 422 }),
      ),
    )

    renderWithProviders(<UploadReceiptPage />)
    await selectFile(user)

    expect(await screen.findByText('ההעלאה נכשלה')).toBeInTheDocument()
  })

  it('lets the user confirm the extracted data and save it', async () => {
    const user = userEvent.setup()
    server.use(
      http.post(UPLOAD_URL, () => HttpResponse.json(successfulExtraction)),
      http.post(CONFIRM_URL, () =>
        HttpResponse.json({
          id: 'expense-9',
          business_name: 'Paz Gas Station',
          receipt_number: '80513',
          amount: '60.13',
          vat_amount: '8.74',
          currency: 'ILS',
          category: 'transport',
          expense_date: '2026-08-22',
          payment_method: null,
          notes: null,
          receipt_image_url: '/uploads/upload-1.png',
          extraction_confidence: 0.82,
          extraction_status: 'confirmed',
          created_at: '2026-08-22T10:00:00',
          updated_at: '2026-08-22T10:00:00',
        }),
      ),
    )

    renderWithProviders(<UploadReceiptPage />)
    await selectFile(user)

    await screen.findByText('סקירה ואישור')
    await user.click(screen.getByRole('button', { name: 'אישור ושמירה' }))

    expect(await screen.findByText('ההוצאה נשמרה. מעביר אתכם לרשימת ההוצאות...')).toBeInTheDocument()
  })

  it('shows a clear message when the receipt was already confirmed', async () => {
    const user = userEvent.setup()
    server.use(
      http.post(UPLOAD_URL, () => HttpResponse.json(successfulExtraction)),
      http.post(CONFIRM_URL, () =>
        HttpResponse.json({ detail: 'This receipt has already been confirmed' }, { status: 409 }),
      ),
    )

    renderWithProviders(<UploadReceiptPage />)
    await selectFile(user)

    await screen.findByText('סקירה ואישור')
    await user.click(screen.getByRole('button', { name: 'אישור ושמירה' }))

    await waitFor(() => {
      expect(screen.getByText('הקבלה הזו כבר אושרה ונשמרה בעבר.')).toBeInTheDocument()
    })
  })

  it('shows the mock-mode label in Hebrew by default', async () => {
    renderWithProviders(<UploadReceiptPage />)
    expect(await screen.findByText('מצב הדגמה — הנתונים מופקים באמצעות מנוע מדומה')).toBeInTheDocument()
  })

  it('shows the mock-mode label in English after switching language', async () => {
    await i18n.changeLanguage('en')
    renderWithProviders(<UploadReceiptPage />)
    expect(await screen.findByText('Demo mode — data is generated by the mock extractor')).toBeInTheDocument()
  })

  it('shows the AI-mode label in Hebrew when the backend reports the openai provider', async () => {
    server.use(
      http.get(CAPABILITIES_URL, () =>
        HttpResponse.json({ receipt_extraction_provider: 'openai', receipt_extraction_mode: 'ai' }),
      ),
    )
    renderWithProviders(<UploadReceiptPage />)
    expect(await screen.findByText('חילוץ AI פעיל')).toBeInTheDocument()
  })

  it('shows the AI-mode label in English when the backend reports the openai provider', async () => {
    await i18n.changeLanguage('en')
    server.use(
      http.get(CAPABILITIES_URL, () =>
        HttpResponse.json({ receipt_extraction_provider: 'openai', receipt_extraction_mode: 'ai' }),
      ),
    )
    renderWithProviders(<UploadReceiptPage />)
    expect(await screen.findByText('AI extraction active')).toBeInTheDocument()
  })

  it('reaches the review form with a partial extraction, showing warnings for missing fields', async () => {
    const user = userEvent.setup()
    server.use(
      http.post(UPLOAD_URL, () =>
        HttpResponse.json({
          upload_id: 'upload-2',
          receipt_image_url: '/uploads/upload-2.png',
          extraction_succeeded: true,
          extracted_data: {
            business_name: null,
            receipt_number: null,
            date: null,
            total: '15.00',
            vat: null,
            currency: 'ILS',
            category: 'other',
            confidence: 0.4,
            warnings: ['business_name_not_confident', 'receipt_number_not_confident'],
          },
          error_message: null,
        }),
      ),
    )

    renderWithProviders(<UploadReceiptPage />)
    await selectFile(user)

    await screen.findByText('סקירה ואישור')
    // Only the fields that were actually found are prefilled; unknowns stay empty.
    expect(screen.getByDisplayValue(/^15(\.0+)?$/)).toBeInTheDocument()
    expect(screen.getByText(/שם העסק לא זוהה בביטחון מספיק/)).toBeInTheDocument()
  })

  it('allows manual entry when the provider fails, without blocking the workflow', async () => {
    const user = userEvent.setup()
    server.use(
      http.post(UPLOAD_URL, () =>
        HttpResponse.json({
          upload_id: 'upload-3',
          receipt_image_url: '/uploads/upload-3.png',
          extraction_succeeded: false,
          extracted_data: null,
          error_message: 'Receipt extraction failed: provider unavailable',
        }),
      ),
      http.post(CONFIRM_URL, () =>
        HttpResponse.json({
          id: 'expense-manual',
          business_name: 'Manual Entry',
          receipt_number: null,
          amount: '10.00',
          vat_amount: null,
          currency: 'ILS',
          category: 'other',
          expense_date: '2026-01-01',
          payment_method: null,
          notes: null,
          receipt_image_url: '/uploads/upload-3.png',
          extraction_confidence: null,
          extraction_status: 'confirmed',
          created_at: '2026-01-01T10:00:00',
          updated_at: '2026-01-01T10:00:00',
        }),
      ),
    )

    renderWithProviders(<UploadReceiptPage />)
    await selectFile(user)

    expect(await screen.findByText('החילוץ האוטומטי נכשל')).toBeInTheDocument()
    // The review/confirm form is still available for manual entry.
    const businessNameInput = screen.getByLabelText(/שם העסק/)
    await user.type(businessNameInput, 'Manual Entry')
    await user.click(screen.getByRole('button', { name: 'אישור ושמירה' }))

    expect(await screen.findByText('ההוצאה נשמרה. מעביר אתכם לרשימת ההוצאות...')).toBeInTheDocument()
  })
})
